### PR TITLE
Rust bindings for C++ geom2graph powered by GEOS

### LINKED ISSUE #92: geom2graph tool broken in 3D
Geos noding API implicitly ignores z coordinates. So the line-line intersection, and threshold snapping only happens in the xy plane.

SFCGAL is insufficient, because it doesn't provide snapping noders (that I could tell). It's 3D graph generation tool required pre-noded input.

Related to #81, #87, and #78

### LINKED ISSUE #130: Rust bindings for geom2graph
See also #129. Simplification is easier if there are no overlaps or duplicates.

On modern hardware, it's probably okay to copy all of the geometries from their C++ geos types to their clean Rust geo equivalents. I do not know if I can use the geos-sys bindings for this.

### LINKED ISSUE #165: Replace GENERATIVE_CARGO_ environment variables with cargo features

### PR DESCRIPTION
**Pull request by Notgnoshi**
Closes #130 
Closes #165 
Closes #92 by removing 3D WKT parsing support

* [x] geom2graph library
  * [x] flatten geoms
  * [x] create GeometryCollectionShim
  * [x] unpack GeometryCollectionShim into a geos GeometryCollection
  * [x] node the collection - use the IteratedNoder instead of SnappingNoder, and catch any exceptions
  * [x] create a c++ GeometryGraph
  * [x] wrap in a Rust GeometryGraphShim
  * [x] unpack GeometryGraphShim into Rust GeometryGraph (petgraph)
  * [x] replicate the C++ tests in Rust
  * [x] wrapper layer to hide the FFI details
* [x] graph2geom library
  * [x] Convert Rust GeometryGraph to GeometryGraphShim
  * [x] Convert GeometryGraphShim into a `std::vec<Geometry*>` (LineString) edges
  * [x] Polygonizer
  * [x] Pass Polygons and Dangles back to Rust side
  * [ ] Maybe write Polygonizer in Rust???
  * [x] wrapper layer to hide the FFI details
* [x] geom2graph binary
  * [x] geom2graph
  * [x] graph2geom
  * [x] test against C++ tool
  * [ ] remove C++ tool
  * [x] optionally snap the results
  * [x] edit README and examples
* [x] build the bindings in the CI pipeline
  * [x] provide Ninja / Make
  * [x] provide g++
  * [x] update geos submodule
  * [x] Remove GENERATIVE_CARGO environment variable in favor of features #165
  * [x] add --all-features
  * [x] build and run C++ tests too

### CODE REVIEW

**Comment by Notgnoshi** [comment]
By adding the bindings directly to `generative`, now every Rust tool transitively depends on `liblog4cplus` and `libgeos`

**Comment by Notgnoshi** [comment]
The `IteratedNoder` can fail to converge, and throw a TopologyException if it does so

image

File: generative/cxxbridge/noder.hpp [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+{
+    const auto geos_geoms = copy_rust_collection_to_geos(rust_geoms);
+    auto noded = std::unique_ptr<geos::geom::Geometry>(nullptr);
+    if (tolerance == 0.0)
+    {
+        noded = generative::noding::GeometryNoder::node(*geos_geoms, nullptr);
+    } else
+    {
+        auto noder = std::make_unique<geos::noding::snap::SnappingNoder>(tolerance);
+        noded = generative::noding::GeometryNoder::node(*geos_geoms, std::move(noder));
```
Comment (Notgnoshi) [inline generative/cxxbridge/noder.hpp:28]: The `IteratedNoder` can fail to converge, and throw a TopologyException if it does so

image

Increasing the number of iterations didn't work :sob:

There's two options:
1. Use the SnappingNoder instead of the IteratedNoder in these cases
   1. Choose the noder with a CLI argument
   2. Don't use the Rust k-D Tree snapping, and use the SnappingNoder whenever --snap is given
3. Catch the error, don't crash, but also don't resolve
4. Catch the error, and retry with the SnappingNoder

Always using the SnappingNoder sucks because then you lose any isolated POINTs that aren't attached to a segment when noding.

It _is_ possible to detect any points that aren't in the noded graph and resolve, _except_ that if those points are on top of a segment, that segment will not be noded.

Given all these cons, and an utter lack of pros, I think there should be a --snapping-noder CLI option
